fix: changes init WindowHandle for Windows App SDK
nventive/MessageDialogService pull request #39
Opened 2022-08-31 22:05 UTC by GabrielChouinardLetourneau

GitHub Issue: #

## Proposed Changes

## What is the current behavior?

We are unable to show a Message Dialog in a Windows App. 
An exception is thrown when the ShowMessage is called.
`Invalid window handle. (0x80070578)
Consider WindowNative, InitializeWithWindow
See https://aka.ms/cswinrt/interop#windows-sdk`

## What is the new behavior?

An initialization was added just before the `ShowAsync` coming from the `MessageDialog` from `Windows.UI.Popups`. 
The MessageDialogService should now be initiated with a `IntPtr` returned by `WinRT.Interop.WindowNative.GetWindowHandle()` with the window as an argument.

## Checklist

Please check if your PR fulfills the following requirements:

- [ ] Documentation has been added/updated
- [ ] Automated Unit / Integration tests for the changes have been added/updated
- [ ] Contains **NO** breaking changes
- [ ] Updated the Changelog
- [ ] Associated with an issue

## Other information

2022-09-01 13:52 UTC, jeanplevesque commented on Shared/MessageDialogBuilderDelegate.cs
> +#if WINUI && WINDOWS10_0_18362_0_OR_GREATER
Do you even target lower than 18362?

2022-09-01 13:52 UTC, jeanplevesque commented on Shared/MessageDialogBuilderDelegate.cs
> +			private IntPtr _hwnd;
that's not a very clear field name

2022-09-01 14:05 UTC, GabrielChouinardLetourneau commented on Shared/MessageDialogBuilderDelegate.cs
> +#if WINUI && WINDOWS10_0_18362_0_OR_GREATER
Technically no, but the other target like `netstandard2.0` had issues with `WinRT` in the sense that they couldn't find it in the context

2022-09-02 21:39 UTC, GabrielChouinardLetourneau commented
A commit will be made to add a `Windows App SDK` entry and to iterate on the **Getting Started** section.

2022-09-06 15:20 UTC, jeanplevesque requested changes

2022-09-06 15:20 UTC, jeanplevesque commented on Shared/MessageDialogBuilderDelegate.cs
> +		/// <param name="windowHandle"></param>
Add xml doc

2022-09-06 15:20 UTC, jeanplevesque commented on Shared/MessageDialogBuilderDelegate.cs
> +		public MessageDialogBuilderDelegate(Func<string, string> resourcesProvider, IntPtr? windowHandle)
Is the windowHandle required on all platforms? It should be clear.

2022-09-06 15:20 UTC, jeanplevesque commented on Shared/MessageDialogBuilderDelegateExtensions.cs
> +	public static partial class MessageDialogBuilderDelegateExtensions
The file name and class name don't seem to have anything to do with the content of the class.

2022-09-06 18:43 UTC, jeanplevesque requested changes

2022-09-06 18:43 UTC, jeanplevesque commented on Shared/Extensions/CollectionExtensions.cs
> -	public static partial class MessageDialogBuilderDelegateExtensions
this class should be internal

2022-09-06 18:43 UTC, jeanplevesque commented on Shared/Extensions/EnumerableExtensions.cs
> +	public static partial class EnumerableExtensions
this class should be internal

2022-09-06 19:09 UTC, jeanplevesque commented on README.md
> +						.TitleResource("Title")
too much indentation here

2022-09-06 19:09 UTC, jeanplevesque commented on README.md
>  # Project Title
This should be "MessageDialogService" instead of "Project Title"

2022-09-06 19:09 UTC, jeanplevesque commented on README.md
> +Message Dialog Service
You can remove this line

2022-09-06 19:09 UTC, jeanplevesque commented on README.md
> +				new MessageDialogBuilderDelegate(
same here, too much indentation

2022-09-06 19:09 UTC, jeanplevesque commented on src/MessageDialog.Uno.WinUI/Extensions/DispatcherQueueExtensions.cs
> +// The .NET Foundation licenses this file to you under the MIT license.
This repository (like all our repos) is under the Apache-2 license.
I'm not sure this header is right.

2022-09-06 21:04 UTC, jeanplevesque approved these changes

2022-09-06 21:22 UTC, merged